def Nameerr():
    try:
        a=5
        print(b)
    except NameError as err:
        print(err)
Nameerr()
